const sourceMetadata = {
  'fullmetal-alchemist-brotherhood-edward': {
    url: 'https://www.hagaren.jp/fa/characters/index01.html',
    sourceTitle: 'Fullmetal Alchemist: Brotherhood - Official Character Profiles',
    sourceType: 'official-anime-character-profile',
    animeTitle: 'Fullmetal Alchemist: Brotherhood',
    releaseMilestone: 'TV anime (2009-2010)',
  },
  'fullmetal-alchemist-sacred-star-edward': {
    url: 'https://www.hagaren-movie.net/character/',
    sourceTitle: 'The Sacred Star of Milos - Character profiles',
    sourceType: 'official-anime-character-profile',
    animeTitle: 'Fullmetal Alchemist: The Sacred Star of Milos',
    releaseMilestone: 'Feature film (2011)',
  },
  'kaguya-sama-ultra-romantic-kaguya': {
    url: 'https://kaguya.love/3rd/character/',
    sourceTitle: 'Kaguya-sama: Love Is War - Ultra Romantic - Characters',
    sourceType: 'official-anime-character-profile',
    animeTitle: 'Kaguya-sama: Love Is War - Ultra Romantic',
    releaseMilestone: 'TV anime season 3 (2022)',
  },
  'gintama-takasugi': {
    url: 'https://www.tv-tokyo.co.jp/anime/gintama/chara/kihei/',
    sourceTitle: 'Gintama - Kiheitai official character profile',
    sourceType: 'official-anime-character-profile',
    animeTitle: 'Gintama anime franchise',
    releaseMilestone: 'Mainline character profile; original episode/cutoff date not listed',
  },
  'frieren-official': {
    url: 'https://frieren-anime.jp/character/chara_group1/1-1/',
    sourceTitle: 'Sousou no Frieren - Official Character Profiles',
    sourceType: 'official-anime-character-profile',
    animeTitle: 'Sousou no Frieren',
    releaseMilestone: 'TV anime Season 1 (2023-2024)',
  },
  'steinsgate-official': {
    url: 'http://steinsgate.tv/character/',
    sourceTitle: 'Steins;Gate Anime - Lab Member Profiles',
    sourceType: 'official-anime-character-profile',
    animeTitle: 'Steins;Gate',
    releaseMilestone: 'TV anime (2011)',
  },
  'shingeki-levi-official': {
    url: 'https://shingeki.tv/final/character/',
    sourceTitle: 'Attack on Titan The Final Season - Character Profiles',
    sourceType: 'official-anime-character-profile',
    animeTitle: 'Attack on Titan',
    releaseMilestone: 'The Final Season (2020-2023)',
  },
}

function assertion(sourceId, tagId, sourceTerm, interpretation) {
  return {
    sourceId,
    tagId,
    traitType: 'personality-behavior',
    sourceTerm,
    editorialInterpretation: interpretation,
    confidence: 'medium',
    reviewStatus: 'proposed',
    reviewer: null,
    reviewedAt: null,
    spoiler: false,
    ...sourceMetadata[sourceId],
  }
}

export const characterProfiles = [
  {
    id: 'edward-elric-fmab',
    name: 'Edward Elric',
    series: 'Fullmetal Alchemist: Brotherhood',
    genre: 'action-fantasy',
    genreLabel: 'Hành động / Kỳ ảo',
    archetype: 'protagonist',
    archetypeLabel: 'Chính diện kiên định',
    imageUrl: '/characters/edward.svg',
    releaseMilestone: 'Related feature film: The Sacred Star of Milos (2011); later franchise cutoff not verified',
    releaseSourceUrl: 'https://www.hagaren-movie.net/intro/',
    latestReleaseVerified: false,
    traitCutoffAligned: false,
    assertions: [
      assertion('fullmetal-alchemist-sacred-star-edward', 'acts-under-uncertainty', '猪突猛進型', 'Hồ sơ phim mô tả Edward có xu hướng xông thẳng vào hành động.'),
      assertion('fullmetal-alchemist-brotherhood-edward', 'communicates-directly', '直情径行気味', 'Hồ sơ chính thức mô tả Edward là người bộc trực, thường phản ứng thẳng.'),
      assertion('fullmetal-alchemist-brotherhood-edward', 'reacts-intensely-to-threats-near-loved-ones', '親しい者に危険が及ぶと', 'Cậu phản ứng dữ dội khi người thân cận gặp nguy hiểm.'),
      assertion('fullmetal-alchemist-brotherhood-edward', 'learns-by-doing', '錬成陣なしでモノを錬成', 'Thực hành giả kim thuật không cần trận niệm chú, học hỏi thực chiến nhanh nhạy.'),
      assertion('fullmetal-alchemist-brotherhood-edward', 'takes-responsibility', '元の身体を取り戻すべく', 'Nhận trách nhiệm về sai lầm quá khứ và kiên định tìm cách khôi phục cơ thể cho em trai.'),
      assertion('fullmetal-alchemist-brotherhood-edward', 'advocates-for-fairness', '不条理を許せない', 'Luôn bất bình và lên tiếng trước sự bất công, phi lý.'),
    ],
  },
  {
    id: 'kaguya-shinomiya-ultra-romantic',
    name: 'Kaguya Shinomiya',
    series: 'Kaguya-sama: Love Is War',
    genre: 'psychological-school',
    genreLabel: 'Đấu trí / Học đường',
    archetype: 'strategist',
    archetypeLabel: 'Chiến lược gia / Độc lập',
    imageUrl: '/characters/kaguya.svg',
    releaseMilestone: 'Otona e no Kaidan special (broadcast 2025-12-31; streaming 2026-01-01)',
    releaseSourceUrl: 'https://kaguya.love/onair/',
    latestReleaseVerified: true,
    traitCutoffAligned: false,
    assertions: [
      assertion('kaguya-sama-ultra-romantic-kaguya', 'plans-alternatives', '様々な手段を日々試みている', 'Cô thường thử nhiều cách để khiến Shirogane bày tỏ tình cảm.'),
      assertion('kaguya-sama-ultra-romantic-kaguya', 'pursues-goals-strategically', '白銀から“告らせる”べく', 'Cô chủ động theo đuổi mục tiêu bằng các kế hoạch khác nhau.'),
      assertion('kaguya-sama-ultra-romantic-kaguya', 'resolves-privately', '裏で根回し', 'Thường chọn cách giải quyết kín đáo, riêng tư thay vì công khai.'),
      assertion('kaguya-sama-ultra-romantic-kaguya', 'respects-personal-space', '距離感を保つ', 'Giữ khoảng cách thận trọng và kín đáo trong tương tác xã hội.'),
      assertion('kaguya-sama-ultra-romantic-kaguya', 'communicates-directly', '本心を告げる', 'Khi đến thời khắc quyết định sẽ bộc lộ trực tiếp và thẳng thắn.'),
    ],
  },
  {
    id: 'shinsuke-takasugi-gintama',
    name: 'Shinsuke Takasugi',
    series: 'Gintama',
    genre: 'action-historical',
    genreLabel: 'Hành động / Lịch sử',
    archetype: 'antihero',
    archetypeLabel: 'Thủ lĩnh / Khắc kỷ',
    imageUrl: '/characters/takasugi.svg',
    releaseMilestone: 'Latest franchise anime found: 3-nen Z-gumi Ginpachi-sensei (broadcast ended 2025); trait cutoff not verified',
    releaseSourceUrl: 'https://www.tv-tokyo.co.jp/anime/ginpachi/',
    latestReleaseVerified: false,
    traitCutoffAligned: false,
    assertions: [
      assertion('gintama-takasugi', 'leads-group', '鬼兵隊を率いて', 'Anh đứng đầu nhóm Kiheitai và có khí chất thu hút người khác.'),
      assertion('gintama-takasugi', 'plans-confrontational-action', 'テロを画策する', 'Hồ sơ mô tả anh lập kế hoạch hành động đối đầu quyết liệt.'),
      assertion('gintama-takasugi', 'self-directed', '己の道を貫く', 'Tự định đoạt con đường riêng, kiên định không chịu khuất phục.'),
      assertion('gintama-takasugi', 'honors-commitments', '誓いを果たす', 'Kiên định giữ trọn cam kết và lý tưởng đến cùng.'),
    ],
  },
  {
    id: 'frieren-beyond-journeys-end',
    name: 'Frieren',
    series: 'Sousou no Frieren',
    genre: 'action-fantasy',
    genreLabel: 'Phiêu lưu / Kỳ ảo',
    archetype: 'mentor',
    archetypeLabel: 'Chiêm nghiệm / Trầm tĩnh',
    imageUrl: '/characters/frieren.svg',
    releaseMilestone: 'TV anime Season 1 (2023-2024)',
    releaseSourceUrl: 'https://frieren-anime.jp/',
    latestReleaseVerified: true,
    traitCutoffAligned: true,
    assertions: [
      assertion('frieren-official', 'collaborates', 'フェルンとシュタルクと共に旅をしている', 'Đồng hành, chia sẻ trách nhiệm và phối hợp nhịp nhàng cùng Fern và Stark.'),
      assertion('frieren-official', 'checks-in-on-others', '人間を知りたい', 'Bắt đầu hành trình mới để học cách thấu hiểu cảm xúc con người.'),
      assertion('frieren-official', 'self-directed', 'ずぼらでドライ、魔法オタク', 'Độc lập, tự chủ và say mê nghiên cứu phép thuật theo cách riêng.'),
      assertion('frieren-official', 'prepares-before-action', '慎重に魔法を準備', 'Bình tĩnh quan sát, chuẩn bị kỹ lưỡng và thận trọng trước mọi đối thủ.'),
    ],
  },
  {
    id: 'rintarou-okabe-steinsgate',
    name: 'Rintarou Okabe',
    series: 'Steins;Gate',
    genre: 'scifi-thriller',
    genreLabel: 'Khoa học / Đấu trí',
    archetype: 'protagonist',
    archetypeLabel: 'Sáng tạo / Táo bạo',
    imageUrl: '/characters/okabe.svg',
    releaseMilestone: 'TV anime (2011)',
    releaseSourceUrl: 'http://steinsgate.tv/',
    latestReleaseVerified: true,
    traitCutoffAligned: true,
    assertions: [
      assertion('steinsgate-official', 'experiments-early', '未来ガジェット研究所', 'Đam mê sáng chế, lập phòng thí nghiệm và thử nghiệm sớm cỗ máy thời gian.'),
      assertion('steinsgate-official', 'takes-initiative', 'ラボメンを率いる', 'Chủ động khởi xướng các cuộc họp lab và dẫn dắt hành động.'),
      assertion('steinsgate-official', 'plans-alternatives', '世界線の分岐を探る', 'Kiên trì tìm kiếm và thử nghiệm vô số phương án nhằm thay đổi kết cục.'),
      assertion('steinsgate-official', 'acts-under-uncertainty', '狂気のマッドサイエンティスト', 'Dám dấn thân vào các vòng lặp bất định để tìm ra dòng thời gian Steins Gate.'),
    ],
  },
  {
    id: 'levi-ackerman-aot',
    name: 'Levi Ackerman',
    series: 'Attack on Titan',
    genre: 'action-fantasy',
    genreLabel: 'Hành động / Kỳ ảo',
    archetype: 'antihero',
    archetypeLabel: 'Kỷ luật / Quyết đoán',
    imageUrl: '/characters/levi.svg',
    releaseMilestone: 'The Final Season (2020-2023)',
    releaseSourceUrl: 'https://shingeki.tv/final/',
    latestReleaseVerified: true,
    traitCutoffAligned: true,
    assertions: [
      assertion('shingeki-levi-official', 'communicates-directly', '歯に衣着せぬ物言い', 'Cách nói chuyện trực diện, ngắn gọn và không né tránh sự thật.'),
      assertion('shingeki-levi-official', 'takes-responsibility', '兵士長の責任', 'Đảm nhận trọng trách chỉ huy và chịu trách nhiệm với sinh mạng cấp dưới.'),
      assertion('shingeki-levi-official', 'prioritizes-shared-deadline', '人類の勝利を優先', 'Đặt việc hoàn thành sứ mệnh chung của Quân Trinh sát lên trên hết.'),
      assertion('shingeki-levi-official', 'honors-commitments', 'エルヴィンとの誓い', 'Giữ trọn lời hứa sắt đá bất chấp hoàn cảnh hiểm nguy.'),
      assertion('shingeki-levi-official', 'self-directed', '人類最強の兵士', 'Khả năng hành động độc lập xuất sắc và tự quyết trong các tình huống hiểm nghèo.'),
    ],
  },
]