export const traitGroups = {
  behavior: 'personality-behavior',
  quality: 'quality-value',
  ability: 'ability',
  appearance: 'appearance',
  preference: 'preference',
}

export const traitCatalog = {
  'offers-peer-support': { label: 'Chủ động hỗ trợ bạn bè', type: traitGroups.behavior },
  collaborates: { label: 'Phối hợp với người khác', type: traitGroups.behavior },
  'takes-responsibility': { label: 'Nhận trách nhiệm phần việc', type: traitGroups.behavior },
  'prioritizes-own-task': { label: 'Ưu tiên phần việc của mình', type: traitGroups.behavior },
  'experiments-early': { label: 'Thử ý tưởng sớm', type: traitGroups.behavior },
  'acts-under-uncertainty': { label: 'Hành động khi chưa chắc chắn', type: traitGroups.behavior },
  'seeks-more-information': { label: 'Tìm thêm thông tin', type: traitGroups.behavior },
  'plans-alternatives': { label: 'Chuẩn bị nhiều phương án', type: traitGroups.behavior },
  'follows-rules': { label: 'Làm theo quy định', type: traitGroups.behavior },
  'communicates-directly': { label: 'Trao đổi thẳng thắn', type: traitGroups.behavior },
  'seeks-rule-exceptions': { label: 'Tìm ngoại lệ theo hoàn cảnh', type: traitGroups.behavior },
  'resolves-privately': { label: 'Giải quyết riêng tư', type: traitGroups.behavior },
  'proposes-process-change': { label: 'Đề xuất thay đổi cách làm', type: traitGroups.behavior },
  'checks-in-on-others': { label: 'Chủ động hỏi thăm', type: traitGroups.behavior },
  'respects-personal-space': { label: 'Tôn trọng không gian riêng', type: traitGroups.behavior },
  'focuses-on-task-impact': { label: 'Tập trung vào ảnh hưởng công việc', type: traitGroups.behavior },
  'leads-group': { label: 'Dẫn dắt nhóm', type: traitGroups.behavior },
  'accepts-group-coordination': { label: 'Chờ nhóm điều phối', type: traitGroups.behavior },
  'takes-initiative': { label: 'Chủ động bắt đầu việc', type: traitGroups.behavior },
  'self-directed': { label: 'Tự xử lý công việc', type: traitGroups.behavior },
  'honors-commitments': { label: 'Giữ cam kết', type: traitGroups.behavior },
  'tries-uncertain-options': { label: 'Thử phương án chưa chắc chắn', type: traitGroups.behavior },
  'communicates-changes': { label: 'Báo rõ khi đổi cách làm', type: traitGroups.behavior },
  'seeks-consensus': { label: 'Tìm sự đồng thuận', type: traitGroups.behavior },
  'supports-with-accountability': { label: 'Hỗ trợ và giữ cam kết chung', type: traitGroups.behavior },
  'adapts-expectations': { label: 'Điều chỉnh kỳ vọng theo hoàn cảnh', type: traitGroups.behavior },
  'prioritizes-shared-deadline': { label: 'Ưu tiên thời hạn chung', type: traitGroups.behavior },
  'redistributes-work': { label: 'Phân lại công việc', type: traitGroups.behavior },
  'facilitates-open-discussion': { label: 'Khuyến khích trao đổi công khai', type: traitGroups.behavior },
  'seeks-common-ground': { label: 'Tìm điểm chung', type: traitGroups.behavior },
  'deescalates-conflict': { label: 'Hạ nhiệt bất đồng', type: traitGroups.behavior },
  'learns-by-doing': { label: 'Học qua thực hành', type: traitGroups.behavior },
  'accepts-mistakes': { label: 'Chấp nhận sai khi học', type: traitGroups.behavior },
  'prepares-before-action': { label: 'Chuẩn bị trước khi làm', type: traitGroups.behavior },
  'seeks-guided-learning': { label: 'Học theo hướng dẫn', type: traitGroups.behavior },
  'advocates-for-fairness': { label: 'Lên tiếng vì công bằng', type: traitGroups.behavior },
  'supports-individuals-privately': { label: 'Hỗ trợ riêng từng người', type: traitGroups.behavior },
  'seeks-authoritative-guidance': { label: 'Hỏi người có thẩm quyền', type: traitGroups.behavior },
  'pursues-goals-strategically': { label: 'Theo đuổi mục tiêu bằng nhiều cách', type: traitGroups.behavior },
  'reacts-intensely-to-threats-near-loved-ones': { label: 'Phản ứng mạnh khi người thân gặp nguy hiểm', type: traitGroups.behavior },
  'plans-confrontational-action': { label: 'Lập kế hoạch đối đầu', type: traitGroups.behavior },
}